disqusShortname = "ocrs"
baseURL = "https://oc-rs.org/"
languageCode = "en-gb"
[permalinks]
  blog = "/:year/:month/:day/:slug/"
[outputs]
  home = ["HTML", "RSS", "JSON"]
[blackfriday] 
  hrefTargetBlank = true

[markup]
[markup.goldmark]
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false