disqusShortname = "ocrs"
baseURL = "https://oc-rs.org/"
languageCode = "en-gb"
[permalinks]
  blog = "/:year/:month/:day/:slug/"
[outputs]
  home = ["HTML", "RSS", "JSON"]
[blackfriday] 
  hrefTargetBlank = true